[package]
name = "io_formats"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
byteorder = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
gloo-net = "0.5"
flate2 = "1.0"
log = "0.4"
base64 = "0.22"
