[package]
name = "neuro_surface"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
io_formats = { path = "../io_formats" }
serde = { version = "1.0", features = ["derive"] }

